import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch();
const url=process.env.FLIPGAIN_TEST_URL||'http://127.0.0.1:5173/';
const next=page=>page.locator('#step-form button[type=submit]').click();
try{
  const context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});
  const page=await context.newPage(),errors=[],apiCalls=[];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('request',request=>{if(['fetch','xhr'].includes(request.resourceType()))apiCalls.push(request.url());});
  await page.goto(url);await page.locator('#name').waitFor();
  assert.equal(await page.locator('input[type=file]').count(),0);
  assert.ok(!(await page.locator('body').innerText()).includes('API'));
  await page.screenshot({path:'mobile-preview.png',fullPage:true,animations:'disabled'});
  await context.setOffline(true);
  await page.locator('#name').fill('Oma testituote');await next(page);
  await page.locator('input[value=electronics]').check();await next(page);
  await page.locator('input[value=good]').check();await page.locator('#details').fill('Toimii, mukana laturi.');await next(page);
  await page.locator('#age').fill('0');await next(page);
  await page.locator('#referencePrice').fill('200');await next(page);
  await page.locator('input[value=trade]').check();await next(page);
  await page.locator('#buy').fill('80');await page.locator('.extra-costs summary').click();await page.locator('#expenses').fill('10');await page.locator('#fee').fill('5');await next(page);
  await page.locator('#analyze').click();assert.match(await page.locator('.price').innerText(),/132,6/);
  await page.locator('#resale').fill('200');await page.locator('#cash').fill('20');await page.locator('#trade-form button[type=submit]').click();assert.match(await page.locator('#trade-result').innerText(),/Vaihto olisi laskennallisesti parempi/);
  await page.locator('#cash').fill('150');assert.equal(await page.locator('#trade-result').innerText(),'');await page.locator('#trade-form button[type=submit]').click();assert.match(await page.locator('#trade-result').innerText(),/Suora myynti olisi laskennallisesti parempi/);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:'result-preview.png',fullPage:true,animations:'disabled'});
  await page.locator('#save-result').click();await page.locator('#toast').filter({hasText:'Tallennettu'}).waitFor();
  await page.locator('#edit-result').click();await page.locator('[data-edit=referencePrice]').click();await page.locator('#referencePrice').fill('100');await next(page);await page.locator('#analyze').click();assert.match(await page.locator('.price').innerText(),/66,3/);
  await context.setOffline(false);await page.reload();await page.locator('#resume').click();await page.locator('#analyze').click();assert.match(await page.locator('.price').innerText(),/66,3/);
  await page.locator('#my-items').click();await page.locator('.saved-item').waitFor();assert.equal(await page.locator('.saved-item').count(),1);await page.locator('[data-open]').click();assert.match(await page.locator('.price').innerText(),/132,6/);
  await page.locator('#my-items').click();await page.locator('[data-delete]').click();await page.waitForFunction(()=>!document.querySelector('.saved-item'));await page.locator('#close-dialog').click();
  await page.locator('#new-product').click();await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'desktop-preview.png',fullPage:true,animations:'disabled'});
  await page.locator('#name').fill('Vanha keräilyesine');await next(page);await page.locator('input[value=collectible]').check();await next(page);await page.locator('input[value=good]').check();await next(page);await page.locator('input[value=profit]').check();await next(page);await next(page);await page.locator('#analyze').click();assert.equal(await page.locator('.price').count(),0);assert.match(await page.locator('.empty-report').innerText(),/asiantuntijan arvio/);
  assert.deepEqual(apiCalls,[]);assert.deepEqual(errors,[]);
  console.log('Passed: no image inputs or API calls, full offline wizard, price/expense calculation, trade comparison, editing, resume, save/reload/delete, collectible refusal, mobile layout.');
}finally{await browser.close();}
