import './style.css';
import './offline.css';
import {conditions,goals,categories,conditionFactors,money,estimate,assessTrade,guidance,draftListing} from './valuation.js';
import {readItems,saveItem,deleteItem} from './storage.js';

const paths={arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',back:'<path d="M19 12H5m5-5-5 5 5 5"/>',trend:'<path d="m3 17 6-6 4 4 8-10m-6 0h6v6"/>',check:'<path d="m5 12 4 4L19 6"/>',spark:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',bookmark:'<path d="M6 21V5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v16l-6-4Z"/>',swap:'<path d="M4 8h16m-4-4 4 4-4 4M20 16H4m4-4-4 4 4 4"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',copy:'<rect x="8" y="8" width="12" height="13" rx="2"/><path d="M16 8V3H3v13h5"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v1"/>',box:'<path d="m12 3 9 5-9 5-9-5 9-5Zm-9 5v9l9 5 9-5V8M12 13v9"/>'};
const icon=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.spark}</svg>`;
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const blank=()=>({name:'',category:'',condition:'',details:'',age:'',referencePrice:'',goal:'',buy:'',expenses:'0',fee:'0'});
const normalize=data=>Object.fromEntries(Object.entries(blank()).map(([key,value])=>[key,typeof data?.[key]==='string'||typeof data?.[key]==='number'?String(data[key]):value]));
const draftKey='flipgain-draft-v3';
let product=blank(),screen='name',result=null,activeId=null,editing=false,draft=null,toastTimer;
try{const stored=JSON.parse(localStorage.getItem(draftKey)||'null');if(stored?.product)draft={...stored,product:normalize(stored.product)};}catch{}
document.querySelector('#app').innerHTML=`<header class="topbar"><button class="brand" id="home" aria-label="Flipgain etusivu">${icon('trend')}flipgain<span>®</span></button><button class="saved-link" id="my-items">${icon('bookmark')} Omat tuotteet</button></header><main id="main"></main><footer><span>Tiedot pysyvät omassa selaimessasi.</span><button id="privacy">Miten arvio toimii?</button></footer><dialog id="dialog"></dialog><div id="toast" role="status"></div>`;
const main=document.querySelector('#main'),dialog=document.querySelector('#dialog');
function notify(text){clearTimeout(toastTimer);const node=document.querySelector('#toast');node.textContent=text;node.classList.add('visible');toastTimer=setTimeout(()=>node.classList.remove('visible'),3500);}
function showDialog(content){dialog.innerHTML=`<button class="close-button" id="close-dialog" aria-label="Sulje">${icon('close')}</button>${content}`;if(!dialog.open)dialog.showModal();document.querySelector('#close-dialog').onclick=()=>dialog.close();}
function steps(){return ['name','category','condition',...(categories[product.category]?.unsupported?[]:['age','referencePrice']),'goal','buy','review'];}
function persist(){if(!product.name.trim())return;try{localStorage.setItem(draftKey,JSON.stringify({product,screen,activeId}));}catch{/* Explicit saves still report failures. */}}
function goto(next){screen=next;persist();render();window.scrollTo({top:0,behavior:'smooth'});requestAnimationFrame(()=>main.querySelector('h1')?.focus({preventScroll:true}));}
function firstMissing(){if(!product.name.trim())return 'name';if(!Object.hasOwn(categories,product.category))return 'category';if(!Object.hasOwn(conditions,product.condition))return 'condition';if(!Object.hasOwn(goals,product.goal))return 'goal';return steps().find(key=>!['buy','review'].includes(key)&&!String(product[key]).trim());}
function progress(){const n=screen==='result'?3:screen==='review'?2:['name','category'].includes(screen)?0:1;return `<ol class="progress" aria-label="Arvion vaiheet">${['Tuote','Tiedot','Tarkistus','Ehdotus'].map((label,i)=>`<li class="${i===n?'current':i<n?'complete':''}" ${i===n?'aria-current="step"':''}><span>${i<n?icon('check'):i+1}</span><b>${label}</b></li>`).join('')}</ol>`;}
function heading(kicker,title,text){return `<div class="intro"><span class="eyebrow">${kicker}</span><h1 tabindex="-1">${title}</h1><p>${text}</p></div>`;}
function buttons(label='Jatka'){return `<div class="form-actions">${screen==='name'?'<span class="local-tag">'+icon('check')+' Ei kuvaa tai kirjautumista</span>':'<button class="back-button" id="back" type="button">'+icon('back')+' Takaisin</button>'}<button class="button primary" type="submit">${editing?'Tallenna muutos':label} ${icon('arrow')}</button></div>`;}
function searchLinks(){return `<div class="market-links"><a href="https://www.tori.fi/recommerce/forsale/search?q=${encodeURIComponent(product.name)}" target="_blank" rel="noopener noreferrer">Vertaa Torissa ↗</a><a href="https://www.facebook.com/marketplace/search/?query=${encodeURIComponent(product.name)}" target="_blank" rel="noopener noreferrer">Vertaa Facebookissa ↗</a></div>`;}
function choice(name,key,title,subtitle,symbol){return `<label class="choice"><input type="radio" name="${name}" value="${key}" ${product[name]===key?'checked':''} required><span class="choice-symbol">${icon(symbol)}</span><span><strong>${title}</strong>${subtitle?`<small>${subtitle}</small>`:''}</span><span class="radio-dot"></span></label>`;}
function render(){
  if(screen==='result')return renderResult();
  let body='';
  if(screen==='name')body=`${heading('VÄHEMMÄN ARVAILUA. SELKEÄMPI PÄÄTÖS.','Mitä haluaisit myydä<br>tai vaihtaa?','Kerro tuotteestasi. Saat hinta-arvion ja apua seuraavaan kauppaan.')}<div class="start-symbol">${icon('box')}</div><form id="step-form"><label for="name">Tuotteen nimi</label><input id="name" name="name" value="${esc(product.name)}" placeholder="Kirjoita merkki ja malli" required maxlength="140" autocomplete="off">${buttons()}</form><p class="privacy-note">${icon('info')} Arvio lasketaan tuoteryhmän, kunnon, iän ja antamasi uushinnan perusteella. Se ei ole markkinahaku.</p>${draft?'<button class="resume-button" id="resume">Jatka keskeneräistä arviota →</button>':''}`;
  if(screen==='category')body=`${heading('TUOTTEESI','Mihin ryhmään tuote kuuluu?','Tuoteryhmä valitsee laskennassa käytettävän arvonalenemissäännön.')}<form id="step-form"><div class="choice-list compact-choices">${Object.entries(categories).map(([key,c])=>choice('category',key,c.label,'','box')).join('')}</div>${buttons()}</form>`;
  if(screen==='condition')body=`${heading('TUOTTEEN KUNTO','Millaisessa kunnossa se on?','Valitse lähin vaihtoehto ja kerro halutessasi lisää.')}<form id="step-form"><div class="choice-list">${Object.entries(conditions).map(([key,label],i)=>choice('condition',key,label,['Kuin uusi, kaikki toimii.','Siisti ja toimiva, pieniä käytön jälkiä.','Toimii, mutta kulumat ovat selviä.','Vika tai toiminta on epävarma.'][i],['spark','check','clock','info'][i])).join('')}</div><label class="notes-label" for="details">Kuvaile tuotetta <span>valinnainen</span></label><textarea id="details" name="details" rows="3" maxlength="2000" placeholder="Kerro vioista, kulumista tai mukana tulevista tarvikkeista…">${esc(product.details)}</textarea><p class="field-hint">Valittu kuntoluokka vaikuttaa laskelmaan. Kuvaus lisätään ilmoitustekstiin; sitä ei tulkita automaattisesti.</p>${buttons()}</form>`;
  if(screen==='age')body=`${heading('TUOTTEEN IKÄ','Kuinka vanha tuote on?','Arvio riittää. Käytä aikaa siitä, kun tuote otettiin uutena käyttöön.')}<form id="step-form"><label for="age">Ikä vuosina</label><div class="money-input"><input id="age" name="age" type="number" inputmode="decimal" min="0" max="100" step="0.1" value="${esc(product.age)}" required placeholder="0"><span>v</span></div><p class="field-hint">Puoli vuotta on 0,5 vuotta. Uusi käyttämätön tuote on 0 vuotta.</p>${buttons()}</form>`;
  if(screen==='referencePrice')body=`${heading('HINNAN LÄHTÖKOHTA','Mitä tuote maksaa uutena?','Anna saman mallin hinta uutena. Jos sitä ei enää myydä, käytä alkuperäistä uushintaa.')}<form id="step-form"><label for="referencePrice">Hinta uutena</label><div class="money-input"><input id="referencePrice" name="referencePrice" type="number" inputmode="decimal" min="0.01" max="1000000" step="0.01" value="${esc(product.referencePrice)}" required placeholder="0"><span>€</span></div><p class="field-hint">Tämä on laskelman vertailuhinta, ei ehdottamasi myyntihinta. Vanhentunut uushinta lisää arvion epävarmuutta.</p>${buttons()}</form>`;
  if(screen==='goal')body=`${heading('SINUN TAVOITTEESI','Millaisen kaupan haluaisit?','Valitse tärkein tavoite.')}<form id="step-form"><div class="choice-list">${Object.entries(goals).map(([key,label],i)=>choice('goal',key,label,['Haluan lähtökohdan hintapyynnölle.','Olen valmis laskemaan hintapyyntöä.','Haluan verrata vaihtoa suoraan myyntiin.'][i],['trend','clock','swap'][i])).join('')}</div>${buttons()}</form>`;
  if(screen==='buy')body=`${heading('VOITON LASKEMINEN','Paljonko itse maksoit?','Hankintahinta tarvitaan vain voiton laskemiseen. Voit jättää sen tyhjäksi.')}<form id="step-form"><label for="buy">Oma hankintahinta <span>valinnainen</span></label><div class="money-input"><input id="buy" name="buy" type="number" inputmode="decimal" min="0" max="1000000" step="0.01" value="${esc(product.buy)}" placeholder="Ei tiedossa"><span>€</span></div><details class="extra-costs" ${Number(product.expenses)||Number(product.fee)?'open':''}><summary>Lisää myyntikulut</summary><label for="expenses">Toimitus, korjaus ja muut kulut (€)</label><input id="expenses" name="expenses" type="number" inputmode="decimal" min="0" max="1000000" step="0.01" value="${esc(product.expenses)}" required><label for="fee">Mahdollinen välityspalkkio (%)</label><input id="fee" name="fee" type="number" inputmode="decimal" min="0" max="99.9" step="0.1" value="${esc(product.fee)}" required></details>${buttons('Tarkista tiedot')}</form>`;
  if(screen==='review')body=`${heading('KAIKKI VALMIINA','Näyttääkö oikealta?','Tarkista tiedot. Arvio valmistuu heti omassa selaimessasi.')}<div class="review-list">${[['name','Tuote',product.name],['category','Tuoteryhmä',categories[product.category]?.label],['condition','Kunto',conditions[product.condition]],['condition','Kuvaus',product.details||'Ei lisäkuvausta'],...(!categories[product.category]?.unsupported?[['age','Ikä',product.age+' vuotta'],['referencePrice','Hinta uutena',money(Number(product.referencePrice))]]:[]),['goal','Tavoite',goals[product.goal]],['buy','Hankintahinta',product.buy===''?'Ei tiedossa':money(Number(product.buy))],['buy','Myyntikulut',`${money(Number(product.expenses))} + ${Number(product.fee)} %`]].map(([key,label,value])=>`<button class="review-row" data-edit="${key}"><span>${label}</span><strong>${esc(value)}</strong><b>Muuta</b></button>`).join('')}</div><p class="error" id="error" role="alert"></p><button class="button primary wide" id="analyze">${icon('spark')} Näytä arvio ${icon('arrow')}</button><p class="privacy-note">${icon('info')} Laskennallinen arvio, ei tarkistettu markkinahinta. Malli ei tunne tuotteen harvinaisuutta tai tämänhetkistä kysyntää.</p>`;
  main.innerHTML=`${progress()}<section class="wizard ${screen==='name'?'text-start':''}">${body}</section>`;
  bind();
}
function bind(){
  const form=document.querySelector('#step-form');
  if(form){
    form.addEventListener('input',()=>{Object.assign(product,Object.fromEntries(new FormData(form)));result=null;persist();});
    form.onsubmit=event=>{event.preventDefault();Object.assign(product,Object.fromEntries(new FormData(form)));if(screen==='name'&&!product.name.trim()){form.elements.name.setCustomValidity('Kirjoita tuotteen nimi.');form.elements.name.reportValidity();form.elements.name.oninput=()=>form.elements.name.setCustomValidity('');return;}if(editing){editing=false;goto(firstMissing()||'review');return;}const order=steps();goto(order[order.indexOf(screen)+1]);};
  }
  document.querySelector('#back')?.addEventListener('click',()=>{if(editing){editing=false;goto('review');return;}const order=steps();goto(order[Math.max(0,order.indexOf(screen)-1)]);});
  document.querySelectorAll('[data-edit]').forEach(button=>button.onclick=()=>{editing=true;goto(button.dataset.edit);});
  document.querySelector('#analyze')?.addEventListener('click',()=>{try{result=estimate(product);goto('result');}catch(error){document.querySelector('#error').textContent=error.message;}});
  document.querySelector('#resume')?.addEventListener('click',()=>{product=normalize(draft.product);activeId=draft.activeId||null;const target=steps().includes(draft.screen)?draft.screen:'review';draft=null;goto(firstMissing()||target);});
}
function renderResult(){
  const r=result,guide=guidance(product),category=categories[product.category];
  main.innerHTML=`${progress()}<section class="results">${heading('SINUN SEURAAVA SIIRTOSI',r.sufficient?'Tässä lähtökohta kaupallesi.':'Tämä tuote tarvitsee oman arvionsa.',r.sufficient?'Suuntaa antava laskelma antamistasi tiedoista.':'Tavallinen arvonalenemismalli ei sovellu tähän tuoteryhmään.')}<div class="result-product"><span class="product-symbol">${icon('box')}</span><div><h2>${esc(product.name)}</h2><p>${esc(category.label)} · ${esc(conditions[product.condition])}</p></div><button class="edit-button" id="edit-result">Muokkaa</button></div>${r.sufficient?`<div class="price-card"><div><span class="eyebrow">LASKENNALLINEN HINTAPYYNTÖ</span><div class="price">${money(r.ask)}</div><span class="price-caption">${product.goal==='quick'?'10 % alle mallin perusarvion':'Lähtökohta omalle hintapyynnöllesi'}</span></div><span class="price-icon">${icon('trend')}</span><div class="price-bottom"><span>Mallin suuntaa antava vaihteluväli</span><strong>${money(r.low)}–${money(r.high)}</strong></div></div><p class="calculation-note">${icon('info')} Hintaväli kuvaa malliin valittua vaihtelua, ei havaittuja kauppoja tai tilastollista luottamusväliä. Todellinen arvo voi olla tämän ulkopuolella.</p><div class="net-grid"><div><span>Käteen myyntikulujen jälkeen</span><strong>${money(r.net)}</strong></div><div><span>${r.profit!==null&&r.profit<0?'Tappio hankintahintaan nähden':'Voitto hankintahintaan nähden'}</span><strong class="${r.profit!==null&&r.profit<0?'negative':''}">${r.profit===null?'Ei tiedossa':`${r.profit>0?'+':''}${money(r.profit)}`}</strong></div></div><p class="field-hint">Jos saat vain vaihteluvälin alarajan, käteen jäisi ${money(r.lowNet)}${r.lowProfit===null?'':` ja ${r.lowProfit<0?'tappiota':'voittoa'} ${money(Math.abs(r.lowProfit))}`}. Kulut ${money(r.expenses)} + ${r.fee} %. Verot ja oman työn hinta eivät sisälly.</p><details class="method result-section"><summary>Mistä hinta muodostuu?</summary><dl class="formula-list"><div><dt>Antamasi hinta uutena</dt><dd>${money(r.reference)}</dd></div><div><dt>Tuoteryhmän lähtökerroin</dt><dd>${Math.round(category.retention*100)} %</dd></div><div><dt>Iän vaikutus (${esc(product.age)} v)</dt><dd>× ${r.ageFactor.toFixed(3)}</dd></div><div><dt>Kunnon vaikutus</dt><dd>× ${conditionFactors[product.condition]}</dd></div><div><dt>Tavoite</dt><dd>${product.goal==='quick'?'× 0,9':'× 1'}</dd></div></dl><p>Hinta = uushinta × tuoteryhmän kerroin × e<sup>−${category.decay} × ikä</sup> × kuntokerroin × tavoitekerroin. Kertoimet ovat tämän työkalun suunnitteluoletuksia, eivät markkinadatasta opittuja arvoja. Tuotteen nimeä tai vapaata kuvausta ei käytetä hinnan laskemiseen.</p></details>`:`<div class="empty-report"><p>${esc(r.reason)}</p>${searchLinks()}</div>`}<section class="result-section"><h2>${icon('clock')} Mikä vaikuttaa myymiseen?</h2><p>${esc(guide.ease)}</p><p class="field-hint">Tuotekohtaista kysyntää tai myyntiaikaa ei ole mitattu.</p></section>
  ${r.sufficient?`<section class="result-section trade-section"><h2>${icon('swap')} Kannattaisiko vaihto?</h2><p>Etsi vaihtokohdetta, jonka jälleenmyynnistä jäisi kulujen ja välirahan jälkeen yli <strong>${money(r.net)}</strong>. Silloin vaihto olisi näillä oletuksilla suoraa myyntiä parempi.</p><details id="trade-details" ${product.goal==='trade'?'open':''}><summary>Laske saamasi vaihtotarjous</summary><form id="trade-form"><label for="resale">Saadun tuotteen jälleenmyyntiarvio (€)</label><input id="resale" name="resale" type="number" inputmode="decimal" min="0" max="1000000" step="0.01" required placeholder="Oma perusteltu arviosi"><div class="trade-fields"><div><label for="cash">Väliraha (€)</label><input id="cash" name="cash" type="number" inputmode="decimal" min="0" max="1000000" step="0.01" value="0" required></div><div><label for="direction">Välirahan suunta</label><select id="direction" name="direction"><option value="pay">Minä maksan</option><option value="receive">Minä saan</option></select></div><div><label for="trade-costs">Vaihtotuotteen myyntikulut (€)</label><input id="trade-costs" name="costs" type="number" inputmode="decimal" min="0" max="1000000" step="0.01" value="0" required></div><div><label for="trade-fee">Välityspalkkio (%)</label><input id="trade-fee" name="fee" type="number" inputmode="decimal" min="0" max="99.9" step="0.1" value="0" required></div></div><button class="button secondary" type="submit">Vertaa suoraan myyntiin ${icon('arrow')}</button><div id="trade-result" role="status"></div></form></details><p class="field-hint">Laskuri vertailee antamiasi lukuja. Se ei etsi ilmoituksia eikä vahvista myyjän vaihtohalukkuutta.</p></section>`:''}
  <section class="result-section"><h2>${icon('info')} Ennen ilmoituksen julkaisua</h2><ul>${guide.risks.map(text=>`<li>${esc(text)}</li>`).join('')}</ul>${searchLinks()}</section><section class="result-section"><h2>${icon('copy')} Ilmoitusteksti valmiiksi</h2><textarea id="listing-text" aria-label="Muokattava ilmoitusteksti" rows="6">${esc(draftListing(product,r))}</textarea><button class="button secondary" id="copy-listing">${icon('copy')} Kopioi teksti</button></section><div class="result-actions"><button class="button primary" id="save-result">${icon('bookmark')} Tallenna arvio</button><button class="button secondary" id="new-product">Uusi tuote ${icon('arrow')}</button></div></section>`;
  document.querySelector('#edit-result').onclick=()=>goto('review');document.querySelector('#new-product').onclick=startNew;document.querySelector('#save-result').onclick=saveCurrent;
  document.querySelector('#copy-listing').onclick=async()=>{const text=document.querySelector('#listing-text');try{await navigator.clipboard.writeText(text.value);notify('Ilmoitusteksti kopioitu.');}catch{text.focus();text.select();notify('Voit kopioida valitun tekstin selaimen valikosta.');}};
  const form=document.querySelector('#trade-form');
  if(form){form.oninput=()=>{document.querySelector('#trade-result').textContent='';};form.onsubmit=event=>{event.preventDefault();const target=document.querySelector('#trade-result');try{const trade=assessTrade(r,Object.fromEntries(new FormData(form)));target.innerHTML=`<div class="trade-outcome"><strong>${trade.advantage>0?'Vaihto olisi laskennallisesti parempi':trade.advantage<0?'Suora myynti olisi laskennallisesti parempi':'Vaihto ja myynti olisivat samanarvoiset'}</strong><p>Vaihdosta käteen ${money(trade.net)}. Ero suoraan myyntiin ${trade.advantage>0?'+':''}${money(trade.advantage)}.${trade.profit===null?'':` ${trade.profit<0?'Tappio':'Voitto'} alkuperäiseen hankintahintaan nähden ${money(Math.abs(trade.profit))}.`}</p></div>`;}catch(error){target.textContent=error.message;}};}
}
async function saveCurrent(){try{const id=activeId||crypto.randomUUID();await saveItem({id,product:structuredClone(product),result,version:3,date:Date.now()});activeId=id;persist();notify('Tallennettu tämän laitteen selaimeen.');}catch(error){notify(error.message);}}
function startNew(){product=blank();result=null;activeId=null;draft=null;editing=false;try{localStorage.removeItem(draftKey);}catch{}goto('name');}
document.querySelector('#home').onclick=()=>{editing=false;goto('name');};
document.querySelector('#my-items').onclick=async()=>{
  try{const items=(await readItems()).filter(i=>i.id!=='draft'&&i.product).sort((a,b)=>b.date-a.date);showDialog(`<span class="eyebrow">TÄLLÄ LAITTEELLA</span><h2>Omat tuotteet</h2>${items.length?items.map(item=>`<article class="saved-item"><span class="product-symbol">${icon('box')}</span><div><h3>${esc(item.product.name||'Nimetön tuote')}</h3><small>${item.version===3&&item.result?.sufficient?money(item.result.ask):'Täydennä tuotteen tiedot'}</small><button class="text-button" data-open="${esc(item.id)}">Avaa arvio →</button></div><button class="delete-button" data-delete="${esc(item.id)}" aria-label="Poista ${esc(item.product.name)}">${icon('close')}</button></article>`).join(''):'<div class="saved-empty">'+icon('bookmark')+'<p>Tallentamasi tuotteet näkyvät täällä.</p></div>'}<p class="field-hint">Arviot tallennetaan vain tähän selaimeen. Selaimen tietojen tyhjentäminen poistaa tallennukset.</p>`);
  document.querySelectorAll('[data-open]').forEach(button=>button.onclick=()=>{const item=items.find(i=>i.id===button.dataset.open);product=normalize(item.product);activeId=item.id;dialog.close();editing=false;if(firstMissing())return goto(firstMissing());try{result=estimate(product);goto('result');}catch{goto('review');}});
  document.querySelectorAll('[data-delete]').forEach(button=>button.onclick=async()=>{try{await deleteItem(button.dataset.delete);if(activeId===button.dataset.delete)activeId=null;button.closest('article').remove();notify('Tuote poistettu.');}catch(error){notify(error.message);}});
  }catch(error){notify(error.message);}
};
document.querySelector('#privacy').onclick=()=>showDialog(`<span class="eyebrow">NÄIN LASKEMME</span><h2>Arvio syntyy selaimessasi.</h2><p>Flipgain käyttää antamaasi uushintaa, tuoteryhmää, ikää ja kuntoluokkaa. Niistä lasketaan lähtökohta hintapyynnölle ennalta määritetyillä kertoimilla. Kertoimet ovat suunnitteluoletuksia, eivät toteutuneisiin kauppoihin perustuvia tilastoja.</p><p>Tuotteen nimeä ja vapaata kuvausta käytetään ilmoitustekstissä. Niitä ei tulkita tekoälyllä, eikä sovellus hae markkinahintoja. Keräilyn, antiikin ja taiteen hintoja ei arvioida yleisellä mallilla.</p><p>Vaihtolaskuri vertaa itse antamaasi vaihtokohteen jälleenmyyntiarvoa, kuluja ja välirahaa oman tuotteesi myyntiarvioon. Hintapyyntö, nopeampi myynti tai voitto eivät ole taattuja.</p><p>Tuotetietoja ei lähetetä palvelimelle. Luonnos ja tallennetut arviot säilyvät tässä selaimessa. Markkinapaikkalinkit avaavat erillisen sivuston vain niitä painettaessa.</p>`);
render();
