import './style.css';
import { conditions, goals, money, safeUrl, valueProduct, draftListing } from './valuation.js';
import { preparePhoto } from './photo.js';
import { readItems, saveItem, deleteItem } from './storage.js';

const paths = {
  arrow: '<path d="M5 12h14m-5-5 5 5-5 5"/>', back: '<path d="M19 12H5m5-5-5 5 5 5"/>',
  trend: '<path d="m3 17 6-6 4 4 8-10m-6 0h6v6"/>', camera: '<path d="M8 5 9 3h6l1 2h4a2 2 0 0 1 2 2v12H2V7a2 2 0 0 1 2-2Z"/><circle cx="12" cy="12" r="4"/>',
  image: '<rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8" cy="8" r="1"/><path d="m3 17 6-6 4 4 3-3 5 5"/>',
  check: '<path d="m5 12 4 4L19 6"/>', spark: '<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5Z"/>',
  close: '<path d="m6 6 12 12M6 18 18 6"/>', bookmark: '<path d="M6 21V5a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v16l-6-4Z"/>',
  swap: '<path d="M4 8h16m-4-4 4 4-4 4M20 16H4m4-4-4 4 4 4"/>', clock: '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
  copy: '<rect x="8" y="8" width="12" height="13" rx="2"/><path d="M16 8V3H3v13h5"/>', info: '<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v1"/>', pin: '<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/>'
};
const icon = name => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name] || paths.spark}</svg>`;
const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const blank = () => ({ name:'', photo:'', condition:'', details:'', goal:'', tradeInterest:'', location:'', buy:'', expenses:'0', fee:'0' });
const emptyComparisons = () => Array.from({length:3},()=>({price:'',url:''}));
let product = blank(), screen = 'photo', report = null, result = null, source = 'manual', busy = false, photoBusy = false;
let ready = false, controller = null, draft = null, activeId = null;
let comparisons = emptyComparisons(), draftQueue = Promise.resolve();
const apiBase = (import.meta.env.VITE_ANALYSIS_API || (location.hostname.endsWith('github.io') ? '' : '/api')).replace(/\/$/,'');
document.querySelector('#app').innerHTML = `<header class="topbar"><button class="brand" id="home" aria-label="Flipgain etusivu">${icon('trend')}flipgain<span>®</span></button><button class="saved-link" id="my-items">${icon('bookmark')} Omat tuotteet</button></header><main id="main"></main><footer><span>Anna tavarallesi seuraava mahdollisuus.</span><button id="privacy">Tietoa palvelusta</button></footer><dialog id="dialog"></dialog><div id="toast" role="status"></div>`;
const main = document.querySelector('#main'), dialog = document.querySelector('#dialog');
function notify(text) { const node=document.querySelector('#toast');node.textContent=text;node.classList.add('visible');setTimeout(()=>node.classList.remove('visible'),3500); }
function showDialog(content) { dialog.innerHTML=`<button class="close-button" id="close-dialog" aria-label="Sulje">${icon('close')}</button>${content}`;if(!dialog.open)dialog.showModal();document.querySelector('#close-dialog').onclick=()=>dialog.close(); }
function sequence() { return ['photo','name','condition','details','goal',...(product.goal==='trade'?['tradeInterest']:[]),'location','buy','review']; }
function persistDraft() {
  if (!product.photo) return;
  const snapshot=structuredClone({id:'draft',product,screen,comparisons,date:Date.now()});
  draftQueue=draftQueue.catch(()=>{}).then(()=>saveItem(snapshot));draftQueue.catch(()=>{});
}
function goto(next) {
  controller?.abort();controller=null;busy=false;screen=next;persistDraft();render();window.scrollTo({top:0,behavior:'smooth'});
  requestAnimationFrame(()=>main.querySelector('h1')?.focus({preventScroll:true}));
}
function back() { if(screen==='comparisons')return goto('review');const steps=sequence();goto(steps[Math.max(0,steps.indexOf(screen)-1)]); }
function progress() {
  const category=screen==='photo'?0:['loading','comparisons'].includes(screen)?2:screen==='result'?3:1;
  return `<ol class="progress" aria-label="Analyysin vaiheet">${['Tuotekuva','Tiedot','Analyysi','Ehdotukset'].map((label,i)=>`<li class="${i===category?'current':i<category?'complete':''}" ${i===category?'aria-current="step"':''}><span>${i<category?icon('check'):i+1}</span><b>${label}</b></li>`).join('')}</ol>`;
}
function heading(kicker,title,description) { return `<div class="intro"><span class="eyebrow">${kicker}</span><h1 tabindex="-1">${title}</h1><p>${description}</p></div>`; }
function buttons(label='Jatka', optional=false) { return `<div class="form-actions"><button type="button" class="back-button" id="back">${icon('back')} Takaisin</button><button class="button primary" type="submit">${label} ${icon('arrow')}</button></div>${optional?'<button type="button" class="skip" id="skip">Ohita tämä vaihe</button>':''}`; }
function photoThumb() { return product.photo?`<div class="product-chip"><img src="${product.photo}" alt="Oma tuotekuvasi"><span>${esc(product.name || 'Sinun tuotteesi')}</span><span class="chip-check">${icon('check')}</span></div>`:''; }
function searchLinks(query=product.name) { return `<div class="market-links"><a href="https://www.tori.fi/recommerce/forsale/search?q=${encodeURIComponent(query)}" target="_blank" rel="noopener noreferrer">Etsi Torista ↗</a><a href="https://www.facebook.com/marketplace/search/?query=${encodeURIComponent(query)}" target="_blank" rel="noopener noreferrer">Etsi Facebookista ↗</a></div>`; }
function render() {
  if(screen==='result')return renderResult();
  if(screen==='loading') { main.innerHTML=`${progress()}<section class="wizard loading-view"><div class="scan-photo"><img src="${product.photo}" alt="Analysoitava tuote"><span class="scan-line"></span></div>${heading('ANALYYSI KÄYNNISSÄ','Etsitään tuotteesi mahdollisuudet.','Tarkistamme tuotetiedot ja etsimme julkisia vertailuilmoituksia. Tämä voi kestää hetken.')}<div class="loading-status" role="status"><span class="spinner"></span> Haetaan vertailutietoa verkosta…</div><button class="back-button" id="cancel-analysis">Keskeytä ja palaa tietoihin</button></section>`;document.querySelector('#cancel-analysis').onclick=()=>goto('review');return; }
  let content='';
  if(screen==='photo')content=`${heading('JOKAINEN HYVÄ KAUPPA ALKAA TÄSTÄ','Mitä haluaisit myydä<br>tai vaihtaa?','Aloitetaan yhdestä kuvasta. Hoidetaan loput vaihe kerrallaan.')}<div class="photo-panel ${product.photo?'has-photo':''}" id="drop-zone">${product.photo?`<img class="photo-preview" src="${product.photo}" alt="Lisäämäsi tuotekuva"><span class="photo-ready">${icon('check')} Kuva lisätty</span>`:`<div class="upload-art">${icon('camera')}<span class="art-spark">${icon('spark')}</span></div><h2>Tuotteesi kuva tähän</h2><p>Ota selkeä kuva koko tuotteesta.<br>Hyvä valo auttaa tunnistamaan yksityiskohdat.</p>`}<div class="upload-buttons"><button type="button" class="button ${product.photo?'secondary':'primary'}" id="choose-photo">${icon('image')} ${product.photo?'Vaihda kuva':'Valitse kuva'}</button><button type="button" class="button secondary" id="take-photo">${icon('camera')} Ota kuva</button></div><span class="file-hint">JPG, PNG tai WebP · enintään 20 Mt</span><input type="file" id="photo-input" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" hidden><input type="file" id="camera-input" accept="image/*" capture="environment" hidden></div><p class="privacy-note">${icon('info')} ${ready?'Kuva ja tuotetiedot lähetetään OpenAI-palveluun tunnistusta ja analyysiä varten.':'Kuva säilyy tässä selaimessa. Automaattinen kuva- ja verkkohaku odottaa käyttöönottoa; hinnan voi arvioida omista vertailuilmoituksista.'}</p><p class="error" id="error" role="alert"></p>${product.photo?`<button class="button primary wide" id="photo-next">Jatka tuotteen tietoihin ${icon('arrow')}</button>`:''}${draft&&!product.photo?'<button class="resume-button" id="resume">Jatka keskeneräistä tuotetta →</button>':''}<div class="start-notes"><span>${icon('image')} Sinun tuotteesi</span><span>${icon('spark')} Perusteltu hintapyyntö</span><span>${icon('swap')} Myy tai vaihda</span></div>`;
  else if(screen==='name')content=`${heading('TUOTTEEN TIEDOT','Mikä tuote on kyseessä?','Vahvista merkki ja tarkka malli. Ne ratkaisevat, mihin tuotetta verrataan.')}${photoThumb()}<form id="step-form"><label for="name">Tuotteen nimi</label><input id="name" name="name" value="${esc(product.name)}" placeholder="Merkki, malli ja mahdollinen koko" required maxlength="140" autocomplete="off"><p class="field-hint">${report?.identificationNote?esc(report.identificationNote):'Löydät mallin usein tuotteen pohjasta, asetuksista tai kuitista.'}</p>${buttons()}</form>`;
  else if(screen==='condition')content=`${heading('TUOTTEEN TIEDOT','Missä kunnossa se on?','Valitse vaihtoehto, joka kuvaa tuotetta parhaiten.')}<form id="step-form"><div class="choice-list">${Object.entries(conditions).map(([key,label],i)=>`<label class="choice"><input type="radio" name="condition" value="${key}" ${product.condition===key?'checked':''} required><span class="choice-symbol">${['✧','✓','≈','⌁'][i]}</span><span><strong>${label}</strong><small>${['Kuin uusi, kaikki toimii.','Siisti ja toimiva, vähäisiä käytön jälkiä.','Toimii, mutta kulumat näkyvät.','Jotain on rikki tai toiminta on epävarmaa.'][i]}</small></span><span class="radio-dot"></span></label>`).join('')}</div>${buttons()}</form>`;
  else if(screen==='details')content=`${heading('TUOTTEEN TIEDOT','Mitä ostajan pitäisi tietää?','Kerro vioista, iästä ja mukana tulevista tarvikkeista, jos tiedät ne.')}<form id="step-form"><label for="details">Lisätiedot <span>valinnainen</span></label><textarea id="details" name="details" maxlength="2000" rows="5" placeholder="Esimerkiksi ikä, akun kunto, naarmut, kuitti ja mukana tulevat tarvikkeet…">${esc(product.details)}</textarea>${buttons('Jatka',true)}</form>`;
  else if(screen==='goal')content=`${heading('SINUN TAVOITTEESI','Mikä olisi sinulle hyvä kauppa?','Painotamme ehdotuksia valintasi mukaan.')}<form id="step-form"><div class="choice-list">${Object.entries(goals).map(([key,label],i)=>`<label class="choice"><input type="radio" name="goal" value="${key}" ${product.goal===key?'checked':''} required><span class="choice-symbol">${icon(['trend','clock','swap'][i])}</span><span><strong>${label}</strong><small>${['Haluan hyvän hinnan ja voin odottaa.','Haluan tavaran eteenpäin nopeasti.','Haluan tilalle jotain arvokkaampaa tai hyödyllisempää.'][i]}</small></span><span class="radio-dot"></span></label>`).join('')}</div>${buttons()}</form>`;
  else if(screen==='tradeInterest')content=`${heading('VAIHTOKAUPPA','Mitä haluaisit tilalle?','Rajaa vaihtokohteita tai jätä avoimeksi, jos tärkeintä on jälleenmyyntiarvo.')}<form id="step-form"><label for="tradeInterest">Toivottu vaihtokohde <span>valinnainen</span></label><input id="tradeInterest" name="tradeInterest" value="${esc(product.tradeInterest)}" placeholder="Tuote, merkki tai tuoteryhmä" maxlength="200">${buttons('Jatka',true)}</form>`;
  else if(screen==='location')content=`${heading('KAUPAN TIEDOT','Missä tuote sijaitsee?','Paikkakunta auttaa arvioimaan noutokauppaa ja rajaamaan vaihtokohteita.')}<form id="step-form"><label for="location">Paikkakunta</label><div class="input-icon">${icon('pin')}<input id="location" name="location" value="${esc(product.location)}" placeholder="Paikkakunta" required maxlength="100" autocomplete="address-level2"></div><p class="field-hint">Pelkkä paikkakunta riittää. Älä lisää kotiosoitetta.</p>${buttons()}</form>`;
  else if(screen==='buy')content=`${heading('KAUPAN TIEDOT','Paljonko maksoit tuotteesta?','Tämän avulla näytämme, jäisikö myynnistä voittoa. Voit myös ohittaa.')}<form id="step-form"><label for="buy">Hankintahinta <span>valinnainen</span></label><div class="money-input"><input id="buy" name="buy" value="${esc(product.buy)}" type="number" inputmode="decimal" min="0" max="1000000" step="0.01" placeholder="0"><span>€</span></div><details class="extra-costs" ${Number(product.expenses)||Number(product.fee)?'open':''}><summary>Lisää mahdolliset myyntikulut</summary><label for="expenses">Toimitus, kunnostus ja muut kulut (€)</label><input id="expenses" name="expenses" type="number" inputmode="decimal" min="0" max="1000000" step="0.01" value="${esc(product.expenses)}"><label for="fee">Mahdollinen välityspalkkio (%)</label><input id="fee" name="fee" type="number" inputmode="decimal" min="0" max="99.9" step="0.1" value="${esc(product.fee)}"></details>${buttons('Tarkista tiedot',true)}</form>`;
  else if(screen==='review')content=`${heading('VALMIS ANALYYSIIN','Näyttääkö kaikki oikealta?','Voit muuttaa tietoja ennen hintavertailua.')}<div class="review-product"><img src="${product.photo}" alt="Oma tuotekuvasi"><div><span class="eyebrow">SINUN TUOTTEESI</span><h2>${esc(product.name)}</h2><span>${esc(conditions[product.condition])}</span></div></div><div class="review-list">${[['name','Tuote',product.name],['condition','Kunto',conditions[product.condition]],['details','Lisätiedot',product.details||'Ei lisätietoja'],['goal','Tavoite',goals[product.goal]],...(product.goal==='trade'?[['tradeInterest','Tilalle',product.tradeInterest||'Avoin ehdotuksille']]:[]),['location','Paikkakunta',product.location],['buy','Hankintahinta',product.buy===''?'Ei tiedossa':money(Number(product.buy))],['buy','Myyntikulut',`${money(Number(product.expenses))} + ${Number(product.fee)} %`]].map(([step,label,value])=>`<button class="review-row" data-edit="${step}"><span>${label}</span><strong>${esc(value)}</strong><b>Muuta</b></button>`).join('')}</div>${ready?'<p class="privacy-note">Kuva ja yllä olevat tiedot lähetetään OpenAI-palveluun. Hintasuositus perustuu löydettyihin julkisiin pyyntihintoihin.</p>':'<div class="service-note">'+icon('info')+'<div><strong>Automaattinen analyysi ei ole vielä käytössä.</strong><p>Voit tehdä perustellun hintavertailun lisäämällä kolmen samanlaisen tuotteen pyyntihinnat.</p></div></div>'}<p id="error" class="error" role="alert"></p><button class="button primary wide" id="analyze">${icon('spark')} ${ready?'Analysoi tuotteeni':'Lisää vertailuilmoitusten hinnat'} ${icon('arrow')}</button><button class="skip" id="save-draft">Tallenna tuote ja jatka myöhemmin</button>`;
  else if(screen==='comparisons')content=`${heading('HINTAVERTAILU','Mitä vastaavista pyydetään?','Lisää vähintään kolme eri ilmoitusta samasta mallista ja vastaavassa kunnossa.')}${searchLinks()}<p class="field-hint">Hakupainikkeet avaavat markkinapaikan. Kopioi hinnat euroina ja halutessasi ilmoituslinkit. Näitä tietoja ei haeta automaattisesti.</p><form id="step-form"><div class="comparisons">${comparisons.map((c,i)=>`<fieldset><legend>Vertailuilmoitus ${i+1}</legend><div class="money-input"><input aria-label="Vertailuhinta ${i+1}" name="price${i}" value="${esc(c.price)}" type="number" inputmode="decimal" min="0.01" max="1000000" step="0.01" required placeholder="Pyyntihinta"><span>€</span></div><input aria-label="Ilmoituslinkki ${i+1}" name="url${i}" value="${esc(c.url)}" type="url" placeholder="Ilmoituslinkki (valinnainen)"></fieldset>`).join('')}</div><p id="error" class="error" role="alert"></p>${buttons('Näytä ehdotus')}</form>`;
  main.innerHTML=`${progress()}<section class="wizard ${screen==='photo'?'photo-step':''}">${content}</section>`;bind();
}
function bind() {
  document.querySelector('#back')?.addEventListener('click',back);
  document.querySelectorAll('[data-edit]').forEach(button=>button.onclick=()=>goto(button.dataset.edit));
  document.querySelector('#resume')?.addEventListener('click',()=>{product=draft.product;comparisons=draft.comparisons||comparisons;goto(sequence().includes(draft.screen)?draft.screen:'review');});
  const form=document.querySelector('#step-form');
  if(form) {
    form.addEventListener('input',()=>{const data=Object.fromEntries(new FormData(form));if(screen==='comparisons')comparisons=comparisons.map((c,i)=>({price:data['price'+i]||'',url:data['url'+i]||''}));else Object.assign(product,data);persistDraft();});
    form.onsubmit=e=>{e.preventDefault();if(screen==='comparisons')return finishManual();if(['name','location'].includes(screen)&&!product[screen].trim()){const field=form.elements[screen];field.setCustomValidity('Täytä tämä tieto.');field.reportValidity();field.oninput=()=>field.setCustomValidity('');return;}const steps=sequence();goto(steps[steps.indexOf(screen)+1]);};
    document.querySelector('#skip')?.addEventListener('click',()=>{if(screen==='buy'){if(!form.elements.expenses.reportValidity()||!form.elements.fee.reportValidity())return;product.buy='';}else product[screen]='';const steps=sequence();goto(steps[steps.indexOf(screen)+1]);});
  }
  document.querySelector('#analyze')?.addEventListener('click',()=>ready?analyze():goto('comparisons'));
  document.querySelector('#save-draft')?.addEventListener('click',()=>saveCurrent(false));
  if(screen==='photo') {
    const photoInput=document.querySelector('#photo-input'),cameraInput=document.querySelector('#camera-input');
    document.querySelector('#choose-photo').onclick=()=>photoInput.click();document.querySelector('#take-photo').onclick=()=>cameraInput.click();
    photoInput.onchange=()=>upload(photoInput.files[0]);cameraInput.onchange=()=>upload(cameraInput.files[0]);
    const drop=document.querySelector('#drop-zone');drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag-over');};drop.ondragleave=()=>drop.classList.remove('drag-over');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('drag-over');upload(e.dataTransfer.files[0]);};
    document.querySelector('#photo-next')?.addEventListener('click',identify);
  }
}
async function upload(file) {
  if(photoBusy||!file)return;photoBusy=true;const currentScreen=screen;document.querySelector('#error').textContent='';document.querySelectorAll('.upload-buttons button').forEach(b=>b.disabled=true);const next=document.querySelector('#photo-next');if(next)next.disabled=true;
  try {const photo=await preparePhoto(file);if(screen!==currentScreen)return;product.photo=photo;report=null;result=null;persistDraft();}
  catch(error){if(screen===currentScreen)document.querySelector('#error').textContent=error.message;photoBusy=false;document.querySelectorAll('.upload-buttons button').forEach(b=>b.disabled=false);if(next)next.disabled=false;return;}
  finally {photoBusy=false;}
  if(screen===currentScreen)render();
}
async function api(path,body,signal) {
  if(!apiBase)throw new Error('Automaattista analyysipalvelua ei ole kytketty.');
  const response=await fetch(`${apiBase}/${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.any([signal,AbortSignal.timeout(150000)])});
  const data=await response.json().catch(()=>({error:'Analyysipalvelu ei vastannut oikein.'}));if(!response.ok)throw new Error(data.error||'Analyysi ei onnistunut. Yritä uudelleen.');return data;
}
async function identify() {
  if(!ready||product.name)return goto('name');if(busy)return;busy=true;controller=new AbortController();const button=document.querySelector('#photo-next');button.disabled=true;button.innerHTML=`<span class="spinner"></span> Tunnistetaan tuotetta…`;
  try {const data=await api('identify',{photo:product.photo},controller.signal);product.name=data.name||'';report={identificationNote:data.note};goto('name');}
  catch(error){if(error.name==='AbortError')return;goto('name');notify('Kuvatunnistus ei onnistunut. Kirjoita tuotteen nimi itse.');}
}
async function analyze() {
  goto('loading');busy=true;controller=new AbortController();
  try {report=await api('analyze',{product},controller.signal);source='web';result=valueProduct(product,report.comparables);goto('result');}
  catch(error){if(error.name==='AbortError')return;goto('review');document.querySelector('#error').textContent=error.name==='TimeoutError'?'Haku kesti liian kauan. Voit yrittää uudelleen.':error.message;const alternative=document.createElement('button');alternative.className='skip';alternative.textContent='Lisää vertailuilmoitukset itse';alternative.onclick=()=>goto('comparisons');document.querySelector('#error').after(alternative);}
}
function finishManual() {
  const urls=comparisons.map(c=>c.url.trim()).filter(Boolean);
  if(urls.some(url=>!safeUrl(url))){document.querySelector('#error').textContent='Käytä https-alkuisia ilmoituslinkkejä.';return;}
  if(new Set(urls).size!==urls.length){document.querySelector('#error').textContent='Lisää kolme eri ilmoitusta. Sama linkki on mukana useasti.';return;}
  const comps=comparisons.map(c=>({title:product.name,price:Number(c.price),url:c.url.trim(),currency:'EUR',comparable:true,condition:conditions[product.condition],priceType:'asking'}));
  try{result=valueProduct(product,comps);report=null;source='manual';goto('result');}catch(error){document.querySelector('#error').textContent=error.message;}
}
function renderResult() {
  const v=result,enough=v?.sufficient,trades=report?.trades||[];
  main.innerHTML=`${progress()}<section class="results">${heading('SINUN SEURAAVA SIIRTOSI',enough?'Tuotteesi, uusi mahdollisuus.':'Tarvitaan vielä vertailutietoa.',enough?(source==='web'?'Ehdotus perustuu verkosta löydettyihin vertailuilmoituksiin.':'Ehdotus perustuu itse lisäämiisi vertailuhintoihin.'):'Luotettavaa hintapyyntöä ei voi laskea ilman vähintään kolmea vertailukelpoista hintaa.')}<div class="result-product"><img src="${product.photo}" alt="${esc(product.name)}"><div><h2>${esc(product.name)}</h2><p>${esc(conditions[product.condition])} <span>·</span> ${esc(product.location)}</p></div><button class="edit-button" id="edit-result">Muokkaa</button></div>${report?.summary?`<p class="analysis-summary">${esc(report.summary)}</p>`:''}${enough?`<div class="price-card"><div><span class="eyebrow">EHDOTETTU HINTAPYYNTÖ</span><div class="price">${money(v.ask)}</div><span class="price-caption">${product.goal==='quick'?'10 % alle vertailuhintojen mediaanin':'Vertailuhintojen mediaani'}</span></div><span class="price-icon">${icon('trend')}</span><div class="price-bottom"><span>Vertailuilmoitusten hintaväli</span><strong>${money(v.low)}–${money(v.high)}</strong></div></div><div class="net-grid"><div><span>Käteen myyntikulujen jälkeen</span><strong>${money(v.net)}</strong></div><div><span>${v.profit!==null&&v.profit<0?'Tappio hankintahintaan nähden':'Voitto hankintahintaan nähden'}</span><strong class="${v.profit!==null&&v.profit<0?'negative':''}">${v.profit===null?'Ei tiedossa':`${v.profit>0?'+':''}${money(v.profit)}`}</strong></div></div><p class="calculation-note">${icon('info')} Pyyntihinnat eivät ole toteutuneita kauppahintoja. ${product.goal==='quick'?'10 % alennus on hinnoittelutapa, ei lupaus nopeasta myynnistä. ':''}Kulut ${money(v.expenses)} + ${v.fee} %. ${v.buy===null?'Hankintahintaa ei annettu. ':''}Verot ja oman työn hinta eivät sisälly.</p>`:`<div class="empty-report">${icon('info')}<h2>Hintaa ei arvata.</h2><p>Löytyi ${v?.comparables?.length||0} riittävän samanlaista vertailuilmoitusta. Tarkista mallin tarkkuus tai lisää vertailuilmoitukset itse.</p><button class="button primary" id="add-comparisons">Lisää vertailuhinnat ${icon('arrow')}</button></div>`}
  ${report?.sellability?`<section class="result-section"><h2>${icon('clock')} Kuinka helppo tämä on myydä?</h2><p>${esc(report.sellability)}</p><span class="field-hint">Laadullinen arvio. Luotettavaa myyntiaikaa ei voida päätellä pyyntihinnoista.</span></section>`:''}
  <section class="result-section"><div class="section-title"><h2>${icon('image')} Hintavertailun perusteet</h2><span class="count">${v?.comparables?.length||0} ilmoitusta</span></div>${(v?.comparables||[]).map(c=>`<div class="comparable"><div><strong>${esc(c.title||product.name)}</strong><small>${esc(c.condition||'Vastaava kunto')} · Pyyntihinta</small>${safeUrl(c.url)?`<a href="${esc(safeUrl(c.url))}" target="_blank" rel="noopener noreferrer">Avaa lähde ↗</a>`:'<small>Käyttäjän lisäämä hinta · ei lähdelinkkiä</small>'}</div><b>${money(c.price)}</b></div>`).join('')}${report?.searchedAt?`<p class="field-hint">Haku ${new Date(report.searchedAt).toLocaleString('fi-FI')}. Ilmoitusten saatavuus voi muuttua.</p>`:''}${searchLinks()}</section>
  ${product.goal==='trade'?`<section class="result-section trade-section"><h2>${icon('swap')} Vaihtomahdollisuudet</h2><p>Vaihdon arvo riippuu saadun tuotteen realistisesta jälleenmyyntiarvosta, välirahasta ja myyntikuluista.</p>${trades.length?trades.map(t=>`<article class="trade-card"><span class="eyebrow">MAHDOLLINEN VAIHTOKOHDE</span><h3>${esc(t.title)}</h3><p>${esc(t.reason)}</p><div><strong>Pyyntihinta ${money(t.price)}</strong><a href="${esc(safeUrl(t.url))}" target="_blank" rel="noopener noreferrer">Avaa ilmoitus ↗</a></div><small>Myynti-ilmoitus. Myyjän vaihtohalukkuutta tai tuottoa ei ole vahvistettu.</small></article>`).join(''):`<div class="trade-empty"><strong>Vahvistettuja vaihtokohteita ei ole saatavilla.</strong><p>${product.tradeInterest?`Etsi tuotetta ”${esc(product.tradeInterest)}” ja tarkista sen omat vertailuhinnat.`:'Rajaa toivottu vaihtokohde tuotetiedoissa, niin sopivia ilmoituksia on helpompi etsiä.'}</p>${searchLinks(product.tradeInterest||product.name)}</div>`}${enough?`<p class="field-hint">Oman tuotteesi vertailuhintojen mediaani on ${money(v.typical)}. Se on neuvottelun lähtökohta, ei vahvistettu vaihtoarvo.</p>`:''}</section>`:''}
  ${report?.risks?.length?`<section class="result-section"><h2>${icon('info')} Tarkista ennen kauppaa</h2><ul>${report.risks.map(r=>`<li>${esc(r)}</li>`).join('')}</ul></section>`:''}
  ${report?.sources?.length?`<details class="result-section"><summary>Analyysin verkkolähteet</summary><ul>${report.sources.filter(s=>safeUrl(s.url)).map(s=>`<li><a href="${esc(safeUrl(s.url))}" target="_blank" rel="noopener noreferrer">${esc(s.title||new URL(s.url).hostname)}</a></li>`).join('')}</ul></details>`:''}
  ${enough?`<section class="result-section"><h2>${icon('copy')} Ilmoitusteksti valmiiksi</h2><textarea id="listing-text" aria-label="Muokattava ilmoitusteksti" rows="7">${esc(draftListing(product,v))}</textarea><button class="button secondary" id="copy-listing">${icon('copy')} Kopioi ilmoitusteksti</button></section>`:''}<div class="result-actions"><button class="button primary" id="save-result">${icon('bookmark')} Tallenna ${enough?'analyysi':'tuote'}</button><button class="button secondary" id="new-product">Uusi tuote ${icon('arrow')}</button></div></section>`;
  document.querySelector('#edit-result').onclick=()=>goto('review');document.querySelector('#add-comparisons')?.addEventListener('click',()=>goto('comparisons'));document.querySelector('#new-product').onclick=startNew;document.querySelector('#save-result').onclick=()=>saveCurrent(true);
  document.querySelector('#copy-listing')?.addEventListener('click',async()=>{const text=document.querySelector('#listing-text');try{await navigator.clipboard.writeText(text.value);notify('Ilmoitusteksti kopioitu.');}catch{text.focus();text.select();notify('Valitse teksti ja kopioi se selaimen valikosta.');}});
}
async function saveCurrent(withResult) {
  const id=activeId||crypto.randomUUID();try{await saveItem({id,product:structuredClone(product),result:withResult?result:null,report:withResult?report:null,source,comparisons:structuredClone(comparisons),date:Date.now()});activeId=id;notify('Tallennettu tämän laitteen selaimeen.');}catch(error){notify(error.message);}
}
function startNew() {
  controller?.abort();product=blank();result=null;report=null;activeId=null;comparisons=emptyComparisons();screen='photo';draft=null;
  draftQueue=draftQueue.catch(()=>{}).then(()=>deleteItem('draft'));draftQueue.catch(()=>{});render();window.scrollTo({top:0,behavior:'smooth'});
}
document.querySelector('#home').onclick=()=>goto(screen==='loading'?'review':'photo');
document.querySelector('#my-items').onclick=async()=>{
  try{const items=(await readItems()).filter(i=>i.id!=='draft').sort((a,b)=>b.date-a.date);showDialog(`<span class="eyebrow">TÄLLÄ LAITTEELLA</span><h2>Omat tuotteet</h2>${items.length?items.map(i=>`<article class="saved-item"><img src="${i.product.photo}" alt=""><div><h3>${esc(i.product.name||'Nimetön tuote')}</h3><small>${i.result?.sufficient?money(i.result.ask):'Tuotetiedot tallennettu'}</small><button class="text-button" data-open="${esc(i.id)}">Jatka tästä →</button></div><button class="delete-button" data-delete="${esc(i.id)}" aria-label="Poista ${esc(i.product.name)}">${icon('close')}</button></article>`).join(''):'<div class="saved-empty">'+icon('bookmark')+'<p>Tallentamasi tuotteet näkyvät täällä.</p></div>'}<p class="field-hint">Kuvat ja analyysit tallennetaan vain tähän selaimeen. Selaimen tietojen tyhjentäminen poistaa tallennukset.</p>`);
  document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const item=items.find(i=>i.id===b.dataset.open);product=item.product;activeId=item.id;result=item.result;report=item.report;source=item.source;comparisons=item.comparisons||comparisons;dialog.close();goto(result?'result':'review');});
  document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{try{await deleteItem(b.dataset.delete);if(activeId===b.dataset.delete)activeId=null;b.closest('article').remove();notify('Tuote poistettu.');}catch(error){notify(error.message);}});
  }catch(error){notify(error.message);}
};
document.querySelector('#privacy').onclick=()=>showDialog(`<span class="eyebrow">FLIPGAIN</span><h2>Tietoa palvelusta</h2><p>Flipgain auttaa määrittämään hintapyynnön ja vertailemaan myyntiä sekä vaihtoa. Hintapyyntö perustuu vähintään kolmen vastaavan tuotteen pyyntihintojen mediaaniin. Nopean kaupan vaihtoehto vähentää tästä 10 %.</p><p>Automaattisen analyysin ollessa käytössä kuva ja tuotetiedot lähetetään OpenAI-palveluun, joka tunnistaa tuotteen ja hakee julkisia verkkolähteitä. Kirjautumisen takana olevia ilmoituksia ei voida kattavasti hakea. Löydetty myynti-ilmoitus ei tarkoita, että myyjä hyväksyy vaihtoja.</p><p>Ilman analyysipalvelua voit lisätä vertailuilmoitusten hinnat itse. Silloin kuvaa ei lähetetä analysoitavaksi. Kuvat pienennetään selaimessa, ja tallennetut tuotteet säilyvät vain tällä laitteella. Emme tallenna kuvia analyysipalvelumme tietokantaan.</p><p>Hintasuositus ei takaa myyntiä tai voittoa. Pyyntihinnat eivät ole toteutuneita kauppahintoja.</p>`);
render();readItems().then(items=>{draft=items.find(i=>i.id==='draft');if(screen==='photo'&&!product.photo)render();}).catch(()=>{});
if(apiBase)fetch(`${apiBase}/health`,{signal:AbortSignal.timeout(5000)}).then(r=>r.ok?r.json():null).then(data=>{ready=data?.ready===true;if(['photo','review'].includes(screen))render();}).catch(()=>{});
