import {findReference} from './market-references.js';
import {money,priceBases,categories,conditionFactors} from './valuation.js';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function sourceCard(source){return `<article class="source-card"><span class="eyebrow">YKSI JULKINEN VERTAILUILMOITUS</span><h3>${esc(source.title)}</h3><strong class="source-price">${money(source.price)} <small>pyyntihinta</small></strong><p>${esc(source.note)}</p><a href="${source.url}" target="_blank" rel="noopener noreferrer">Tarkista alkuperäinen ilmoitus ↗</a><p class="field-hint">Tallennettu ${source.observedAt}. Ei reaaliaikainen haku eikä toteutunut kauppa. Varmista vuosimalli, akun kunto ja saatavuus.</p></article>`;}
export function pricingFields(product){
  const reference=findReference(product);
  return `${reference?sourceCard(reference):'<div class="service-note"><p>Tälle mallille ja kunnolle ei ole käytettävissä riittävän tuoretta tallennettua hintatietoa. Emme tiedä sen käytettyä markkinahintaa.</p></div>'}<div class="choice-list pricing-choices">${[...(reference?[['reference','Käytä vertailuilmoituksen hintaa','Yhden ilmoituksen pyyntö, ei vahvistettu markkina-arvo.']]:[]),['market','Tiedän käytetyn hintatason','Saman mallin ja vastaavan kunnon hinta.'],['formula','Näytä vain karkea laskelma','Uushinnasta ja iästä. Voi poiketa huomattavasti markkinahinnasta.']].map(([key,title,note])=>`<label class="choice"><input name="priceBasis" type="radio" value="${key}" ${product.priceBasis===key?'checked':''} required><span><strong>${title}</strong><small>${note}</small></span><span class="radio-dot"></span></label>`).join('')}</div><div id="market-fields" ${product.priceBasis==='market'?'':'hidden'}><label class="notes-label" for="marketPrice">Vastaavan käytetyn tuotteen hintataso (€)</label><input id="marketPrice" name="marketPrice" type="number" inputmode="decimal" min="0.01" max="1000000" step="0.01" value="${esc(product.marketPrice)}" placeholder="Tuntemasi hintataso" ${product.priceBasis==='market'?'required':'disabled'}><p class="field-hint">Tätä hintaa ei alenneta uudelleen iän tai kuntoluokan perusteella. Kerro juuri oman tuotteesi kuntoa vastaava hintataso.</p></div>${reference?`<label id="reference-confirmation" class="reference-confirmation" ${product.priceBasis==='reference'?'':'hidden'}><input type="checkbox" name="referenceConfirmed" value="yes" ${product.referenceConfirmed==='yes'?'checked':''} ${product.priceBasis==='reference'?'required':'disabled'}><span>Vertailun versio ja kunto ovat riittävän lähellä omaa tuotettani. Ymmärrän, että kyse on yhdestä pyyntihinnasta.</span></label>`:''}`;
}
export function syncPricingFields(form,product){
  const market=product.priceBasis==='market',reference=product.priceBasis==='reference';
  form.querySelector('#market-fields').hidden=!market;form.elements.marketPrice.disabled=!market;form.elements.marketPrice.required=market;
  const confirmation=form.querySelector('#reference-confirmation');
  if(confirmation){confirmation.hidden=!reference;form.elements.referenceConfirmed.disabled=!reference;form.elements.referenceConfirmed.required=reference;product.referenceConfirmed=reference&&form.elements.referenceConfirmed.checked?'yes':'';}
}
export function pricingRows(product){
  const rows=[['pricing','Hintaperuste',priceBases[product.priceBasis]||'Valitsematta']];
  if(product.priceBasis==='market')rows.push(['pricing','Käytettynä',money(Number(product.marketPrice))]);
  if(product.priceBasis==='reference')rows.push(['pricing','Vertailupyyntö',findReference(product)?money(findReference(product).price):'Vahvista uudelleen']);
  if(product.priceBasis==='formula'&&!categories[product.category]?.unsupported)rows.push(['age','Ikä',product.age+' vuotta'],['referencePrice','Hinta uutena',money(Number(product.referencePrice))]);
  return rows;
}
export function resultIntro(product,r){
  const generic=r.method==='formula';
  return `<div class="intro"><span class="eyebrow">HINTAPERUSTE NÄKYVISSÄ</span><h1 tabindex="-1">${!r.sufficient?'Hintaa ei voi vahvistaa.':generic?'Vain karkea laskelma.':'Hintaperuste ensin, kannattavuus sitten.'}</h1><p>${!r.sufficient?'Tämä tuoteryhmä tarvitsee oman vertailunsa.':generic?'Tämä ei ole tuotekohtainen myyntihintasuositus.':r.method==='market'?'Laskelma perustuu itse antamaasi käytetyn tuotteen hintatasoon.':'Lähtökohtana on yksi tallennettu saman mallin myynti-ilmoitus.'}</p></div>`;
}
export function priceSummary(product,r){
  if(!r.sufficient)return `<div class="empty-report"><p>${esc(r.reason)}</p></div>`;
  const generic=r.method==='formula',category=categories[product.category];
  return `${generic?'<div class="service-note"><strong>Markkinahintaa ei tunneta. Älä käytä tätä lukua ainoana perusteena hinnoittelulle.</strong></div>':''}<div class="price-card"><div><span class="eyebrow">${generic?'YLEISKAAVAN TULOS':r.method==='market'?'OMAAN HINTATIETOOSI PERUSTUVA PYYNTÖ':'VERTAILUPYYNNÖSTÄ LASKETTU LÄHTÖHINTA'}</span><div class="price">${money(r.ask)}</div><span class="price-caption">${product.goal==='quick'?'Valitsemasi nopean kaupan alennus: 10 %':generic?'Ei vahvistettu myyntihinta':'Ikää ja kuntokerrointa ei vähennetä toistamiseen'}</span></div><div class="price-bottom"><span>${generic?'Kaavan vaihteluväli':'Valittu käytetyn hinnan lähtötaso'}</span><strong>${generic?money(r.low)+'–'+money(r.high):money(r.typical)}</strong></div></div><p class="calculation-note">${generic?'Hintaväli on laskentamallin oletus, ei havaittu hintahaarukka.':r.method==='reference'?'Yksi pyyntihinta ei todista toteutuvaa kauppahintaa tai nopeaa myyntiä.':'Käyttäjän ilmoittama hintataso. Sivusto ei ole vahvistanut sitä itsenäisesti.'}</p><div class="net-grid"><div><span>Käteen myyntikulujen jälkeen</span><strong>${money(r.net)}</strong></div><div><span>${r.profit!==null&&r.profit<0?'Tappio hankintahintaan nähden':'Voitto hankintahintaan nähden'}</span><strong class="${r.profit!==null&&r.profit<0?'negative':''}">${r.profit===null?'Ei tiedossa':`${r.profit>0?'+':''}${money(r.profit)}`}</strong></div></div><p class="field-hint">Kulut ${money(r.expenses)} + ${r.fee} %. Verot ja oman työn hinta eivät sisälly.</p>${r.source?sourceCard(r.source):''}${generic?`<details class="method result-section"><summary>Mistä karkea luku muodostuu?</summary><p>${money(r.reference)} × ${category.retention} × e<sup>−${category.decay} × ${esc(product.age)}</sup> × ${conditionFactors[product.condition]} × ${product.goal==='quick'?.9:1}. Kertoimet ovat yleisiä suunnitteluoletuksia. Tuotemallia ja kuvausta ei tulkita. Tämä laskentatapa voi aliarvioida esimerkiksi kysytyn sähköpotkulaudan hinnan huomattavasti.</p></details>`:''}`;
}
